[main] Rename files and variables from hestiacp fork

diff --git a/bin/v-add-sys-pma-sso b/bin/v-add-sys-pma-sso
--- a/bin/v-add-sys-pma-sso
+++ b/bin/v-add-sys-pma-sso
@@ -13,12 +13,12 @@
 MODE=$1
 
 # Includes
-# shellcheck source=/etc/hestiacp/hestia.conf
-source /etc/hestiacp/hestia.conf
-# shellcheck source=/usr/local/hestia/func/main.sh
-source $HESTIA/func/main.sh
+# shellcheck source=/etc/lokahost/lokahost.conf
+source /etc/lokahost/lokahost.conf
+# shellcheck source=/usr/local/lokahost/func/main.sh
+source $LOKAHOST/func/main.sh
 # load config file
-source_conf "$HESTIA/conf/hestia.conf"
+source_conf "$LOKAHOST/conf/lokahost.conf"
 
 PMA_INSTALL="/usr/share/phpmyadmin"
 PMA_CONFIG="/etc/phpmyadmin"
@@ -28,7 +28,7 @@ PMA_CONFIG="/etc/phpmyadmin"
 #----------------------------------------------------------#
 
 # Perform verification if read-only mode is enabled
-check_hestia_demo_mode
+check_lokahost_demo_mode
 
 # Checking root permissions
 if [ "x$(id -u)" != 'x0' ]; then
@@ -41,8 +41,8 @@ if [ -n "$PHPMYADMIN_KEY" ] && [ "$PHPMYADMIN_KEY" != "" ]; then
 	exit 1
 fi
 
-if [ -f "/usr/share/phpmyadmin/hestia-sso.php" ]; then
-	echo "Error: hestia-sso.php is already installed"
+if [ -f "/usr/share/phpmyadmin/lokahost-sso.php" ]; then
+	echo "Error: lokahost-sso.php is already installed"
 	exit 2
 fi
 
@@ -65,35 +65,35 @@ phpmyadminkey=$(generate_password)
 apikey=$($BIN/v-add-access-key 'admin' 'phpmyadmin-sso' 'phpMyAdmin' 'plain')
 
 # copy config dir to /usr/share/phpmyadmin/
-cp -f $HESTIA_INSTALL_DIR/phpmyadmin/hestia-sso.php $PMA_INSTALL/hestia-sso.php
-chmod 640 $PMA_INSTALL/hestia-sso.php
-chown root:www-data $PMA_INSTALL/hestia-sso.php
+cp -f $LOKAHOST_INSTALL_DIR/phpmyadmin/lokahost-sso.php $PMA_INSTALL/lokahost-sso.php
+chmod 640 $PMA_INSTALL/lokahost-sso.php
+chown root:www-data $PMA_INSTALL/lokahost-sso.php
 
-sed -i "s/%PHPMYADMIN_KEY%/$phpmyadminkey/g" $PMA_INSTALL/hestia-sso.php
-sed -i "s/%API_KEY%/$apikey/g" $PMA_INSTALL/hestia-sso.php
-sed -i "s/%API_HOST_NAME%/$(hostname)/g" $PMA_INSTALL/hestia-sso.php
-sed -i "s/%API_HESTIA_PORT%/$BACKEND_PORT/g" $PMA_INSTALL/hestia-sso.php
+sed -i "s/%PHPMYADMIN_KEY%/$phpmyadminkey/g" $PMA_INSTALL/lokahost-sso.php
+sed -i "s/%API_KEY%/$apikey/g" $PMA_INSTALL/lokahost-sso.php
+sed -i "s/%API_HOST_NAME%/$(hostname)/g" $PMA_INSTALL/lokahost-sso.php
+sed -i "s/%API_LOKAHOST_PORT%/$BACKEND_PORT/g" $PMA_INSTALL/lokahost-sso.php
 
 # Check if config already contains the keys
-touch $PMA_CONFIG/hestia-sso.inc.php
-chmod 640 $PMA_CONFIG/hestia-sso.inc.php
-chown root:www-data $PMA_CONFIG/hestia-sso.inc.php
+touch $PMA_CONFIG/lokahost-sso.inc.php
+chmod 640 $PMA_CONFIG/lokahost-sso.inc.php
+chown root:www-data $PMA_CONFIG/lokahost-sso.inc.php
 
 echo "<?php
-if(isset(\$_GET['hestia_token']) || isset(\$_COOKIE['SignonSession'])){
+if(isset(\$_GET['lokahost_token']) || isset(\$_COOKIE['SignonSession'])){
 \$cfg['Servers'][\$i]['auth_type'] = 'signon';
 \$cfg['Servers'][\$i]['SignonSession'] = 'SignonSession';
-\$cfg['Servers'][\$i]['SignonURL'] = 'hestia-sso.php';
-\$cfg['Servers'][\$i]['LogoutURL'] = 'hestia-sso.php?logout=1';
+\$cfg['Servers'][\$i]['SignonURL'] = 'lokahost-sso.php';
+\$cfg['Servers'][\$i]['LogoutURL'] = 'lokahost-sso.php?logout=1';
 }
-?>" >> $PMA_CONFIG/hestia-sso.inc.php
+?>" >> $PMA_CONFIG/lokahost-sso.inc.php
 
 file=$(cat $PMA_CONFIG/config.inc.php)
-if ! [[ "$file" =~ hestia-sso.inc.php ]]; then
-	if [[ $file =~ "//Add Hestia SSO code here" ]]; then
-		sed -i "s|//Add Hestia SSO code here|//Add Hestia SSO code here\n     include ('$PMA_CONFIG/hestia-sso.inc.php');|g" $PMA_CONFIG/config.inc.php
+if ! [[ "$file" =~ lokahost-sso.inc.php ]]; then
+	if [[ $file =~ "//Add Lokahost SSO code here" ]]; then
+		sed -i "s|//Add Lokahost SSO code here|//Add Lokahost SSO code here\n     include ('$PMA_CONFIG/lokahost-sso.inc.php');|g" $PMA_CONFIG/config.inc.php
 	else
-		echo "include ('$PMA_CONFIG/hestia-sso.inc.php');" >> $PMA_CONFIG/config.inc.php
+		echo "include ('$PMA_CONFIG/lokahost-sso.inc.php');" >> $PMA_CONFIG/config.inc.php
 	fi
 fi
 
@@ -108,7 +108,7 @@ fi
 #----------------------------------------------------------#
 
 if [ "$MODE" != "quiet" ]; then
-	echo "PMA Hestia-SSO plugin has been successfully installed"
+	echo "PMA Lokahost-SSO plugin has been successfully installed"
 fi
 $BIN/v-log-action "system" "Info" "Plugins" "phpMyAdmin Single Sign-On has been enabled."
 log_event "$OK" "$ARGUMENTS"
